### ISSUE TITLE
ArgumentOutOfRangeException In DbfRecord

### ISSUE THREAD

**Issue by ahmadfarazm** [henck/dBASE.NET#20]
Hi
I have an exception in DbfRecord  :
Buffer length has exceeded length of the field
I have this exception even with your "Writing a DBF file" sample code

**Comment by KevC0** [comment]
Hi,
I'm getting the same exception.

```
Buffer length has exceeded length of the field. 
Parametername: Length
The actual value was 4.
   at dBASE.NET.DbfRecord.Write(BinaryWriter writer, Encoding encoding)
   at dBASE.NET.Dbf.WriteRecords(BinaryWriter writer)
   at dBASE.NET.Dbf.Write(Stream stream, Boolean leaveOpen)
   at dBASE.NET.Dbf.Write(Stream stream, DbfVersion version)
```
How do I figure out which record is causing the problem?
